---
- hosts: imageMe_nodes
  become: yes
  vars:
    SEARCH_ENGINE_ID: '000873326420470546694:ycmt1tmdzxs'
    GOOGLE_CLOUD_API_KEY: 'AIzaSyBPLn4atC6KfIxY_bTIjG8kjhS-hdqWIJg'
  tasks:
    - command: echo "$PATH"
      register: default_path
    - name: "install git"
      yum:
        name: git
        state: present
    - name: "clone repo"
      git:
        repo: https://github.com/jkanclerz/google-search-python.git
        dest: /home/ec2-user/imageMe/
        force: yes
    - name: "add search engine ID and api key"
      lineinfile:
        dest: "/etc/environment"
        state: present
        regexp: "^{{ item.key }}"
        line: "{{ item.key }}={{ item.value}}"
      with_items: "{{ environment }}"
      environment:
      - key: SEARCH_ENGINE_ID
        value : "{{ SEARCH_ENGINE_ID }}"
      - key: GOOGLE_CLOUD_API_KEY
        value: "{{ GOOGLE_CLOUD_API_KEY }}"
    - name: "create bin directory"
      file: path=/home/ec2-user/bin state=directory
    - name: "Add image_me.py script to PATH"
      copy:
        dest: /bin/image_me
        content: python2 /home/ec2-user/imageMe/image_me.py
    - name: "change permission"
      file:
        path: /bin/image_me
        state: touch
        mode: "u=x,g=x,o=x"
    - name: "run image_me"
      shell: image_me "car"



