---
- hosts: imageMe_nodes
  become: yes
  vars:
    SEARCH_ENGINE_ID: '006879359584856769921:rplfy3clmho'
    GOOGLE_CLOUD_API_KEY: 'AIzaSyDLLC1pqOxkWA8jUjM-Cfwbl_13Sh_2t98'
  tasks:
    - name: "install git"
      yum:
        name: git
        state: present
    - name: "clone repo"
      git:
        repo: https://github.com/jkanclerz/google-search-python.git
        dest: /home/ec2-user/imageMe/
        force: yes
    - name: "set SEARCH_ENGINE_ID env variable"
      shell: "echo 'export SEARCH_ENGINE_ID='{{SEARCH_ENGINE_ID}}'' >> .bashrc"
    - name: "set GOOGLE_CLOUD_API_KEY env variable"
      shell: "echo 'export GOOGLE_CLOUD_API_KEY='{{GOOGLE_CLOUD_API_KEY}}'' >> .bashrc"
    - name: "create bin directory"
      file: path=/home/ec2-user/bin state=directory
    - name: "Add script to bin"
      copy:
        src: ./templates/imageMe.sh
        dest: /home/ec2-user/bin/imageMe.sh
    - name: "change permission"
      file:
        path: /home/ec2-user/bin/imageMe.sh
        state: touch
        mode: "u=rwx,g=rwx,o=rwx"


